const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.HOME + '/Library/Caches/ms-playwright/chromium-1243/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing' });
  const page = await browser.newPage({ viewport: { width: 1700, height: 1000 } });
  await page.goto('http://localhost:5183/agent-next-gen-v3/');
  await page.waitForTimeout(800);
  await page.click('text=Launch');
  await page.waitForTimeout(6000);
  await page.getByText('Go Available').click().catch(()=>{});
  await page.waitForTimeout(600);
  await page.getByText('Agent Workspace 2.0 | Phase 1', { exact: true }).click();
  await page.waitForTimeout(400);
  await page.getByText('Agent Workspace 2.0 | Phase 2', { exact: true }).click();
  await page.waitForTimeout(2500);
  await page.getByText('Go Available').click().catch(()=>{});
  await page.waitForTimeout(800);
  await page.mouse.click(30, 74);
  await page.waitForTimeout(600);
  await page.getByText('Dial Pad').click();
  await page.waitForTimeout(600);
  await page.fill('input[placeholder="(555) 555-5555"]', '2125551234');
  await page.click('text=Dial Number');
  await page.waitForTimeout(4000);
  await page.mouse.click(1623, 131);
  await page.waitForTimeout(600);
  const data = await page.evaluate(() => {
    const popover = Array.from(document.querySelectorAll('div')).find(d => d.textContent?.startsWith('Log Outcome') && d.className.includes('rounded-lyra-lg'));
    const endCallBtn = Array.from(document.querySelectorAll('button')).find(b => b.textContent?.includes('End Call'));
    const r1 = popover?.getBoundingClientRect();
    const r2 = endCallBtn?.getBoundingClientRect();
    return { popover: r1 && {left:r1.left, right:r1.right, top:r1.top, bottom:r1.bottom, width:r1.width}, endCall: r2 && {left:r2.left, right:r2.right, top:r2.top, bottom:r2.bottom} };
  });
  console.log(JSON.stringify(data, null, 2));
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
